### ISSUE TITLE
Incorrect behavior in during sequential PreProcess initialization

### ISSUE THREAD

**Issue by vitalyanich** [InWonYeu/interphon#33]
Dear In Won Yeu,

During the use of your software I faced with another problem. If I try to sequentially initialize two instances of PreProcess with different POSCARS that have different number of atoms, I get the following error:

ValueError                                Traceback (most recent call last)
Input In [3], in <cell line: 15>()
     13 pre.set_user_arg(user_args)
     14 pre.set_unit_cell(path_us_2)
---> 15 pre.set_super_cell(path_ss_2)

File ~\PycharmProjects\interphon\InterPhon\core\pre_process.py:109, in PreProcess.set_super_cell(self, out_file, comment, write_file, code_name)
     93 def set_super_cell(self, out_file: FilePath,
     94                    comment: str = 'Supercell',
     95                    write_file: bool = True,
     96                    code_name: str = 'vasp') -> File:
     97     """
     98     Set a **SuperCell** instance from the information stored in its **UnitCell** and **UserArgument** instances.
     99 
   (...)
    107     :type code_name: str
    108     """
--> 109     self.super_cell.set_super_cell(self.unit_cell, self.user_arg)
    110     self.super_cell.set_super_ind_true(self.unit_cell, self.user_arg)
    111     if write_file is True:

File ~\PycharmProjects\interphon\InterPhon\core\super_cell.py:72, in SuperCell.set_super_cell(self, unit_cell, user_arg)
     69     if value:
     70         _enlarge = _enlarge * user_arg.enlargement[ind]
---> 72 self.atom_type = []
     73 for atom_type in unit_cell.atom_type:
     74     self.atom_type.extend([atom_type for _ in range(_enlarge)])

File ~\PycharmProjects\interphon\InterPhon\core\unit_cell.py:119, in UnitCell.atom_type(self, _atom_type)
    117     self.__atom_type = _atom_type
    118 else:
--> 119     raise ValueError("The length of atom_type should be the total number of atoms")

ValueError: The length of atom_type should be the total number of atoms

How to reproduce:

Just run the following code where (path_us_1, path_ss_1) and (path_us_2, path_ss_2) are the paths to the Unitcell/Supercell having different number of atoms. I used a Jupyter Notebook, python 3.9.

from InterPhon.core import PreProcess

user_args = {'dft_code': 'vasp',
             'displacement': 0.05,
             'enlargement': "1 1 1",
             'periodicity': "1 1 0"}

pre = PreProcess()
pre.set_user_arg(user_args)
pre.set_unit_cell(path_us_1)
pre.set_super_cell(path_ss_1)

pre = PreProcess()
pre.set_user_arg(user_args)
pre.set_unit_cell(path_us_1)
pre.set_super_cell(path_ss_2)

**Comment by InWonYeu** [comment]
If you want to make two instances of PreProcess Class containing different POSCAR information, the instance name should be different, for example:

pre_1 = PreProcess()
pre_1.set_user_arg(user_args)
pre_1.set_unit_cell(path_us_1)
pre_1.set_super_cell(path_ss_1)

pre_2 = PreProcess()
pre_2.set_user_arg(user_args)
pre_2.set_unit_cell(path_us_2)
pre_2.set_super_cell(path_ss_2)

However, If you wanted to just overwrite the first "pre" instance where the first POSCAR information was stored with the second POSCAR information, it looks like the internal process initializing the information stored in the previous instance needs to be added in the python code process. I will check this point and update the code if this can be implemented.

**Comment by InWonYeu** [comment]
The above issues are resolved in the recently released version 1.5.0.
Please check and let me know if there is any additional problem.
Thank you again for your valuable report.

**Comment by vitalyanich** [comment]
Thank you!
